### ISSUE TITLE
`welcome.py` and `jobs.py` run simultaneously

### ISSUE THREAD

**Issue by bradleysigma** [UQComputingSociety/uqcsbot#496]
Now that `#jobs-bulletin` is a default channel, any new user will trigger both `welcome.py` and `jobs.py` when they join, interweaving the two messages.

![image](https://user-images.githubusercontent.com/42644678/68522546-04915600-02f8-11ea-8df4-73e44a38314c.png)

(Also, "#events" on line 26 of `welcome.py` should be a channel link.)

**Comment by kumar-ish** [comment]
Could we just chuck a time.sleep(25), or the duration of the welcome message + 5 seconds, before when the start of the #jobs-bulletin message is sent (and change the WELCOME_MESSAGES so that it says something like "Additionally,  all members of our Slack automatically join #jobs-bulletin. Just so you know, " at the start)? I think that's the best way to fix this since it means that people get introduced to the Slack v fast, and also know not to post something irrelevant to #jobs-bulletin.

**Comment by jdcaperon** [comment]
A valid stop-gap is to remove #jobs-bulletin as a default and instead suggest it as part of the welcome message

**Comment by bradleysigma** [comment]
#jobs-bulletin has been removed as a default.
